id: AA7FF5140
base_file: fA915.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:48:59.526036
  last_modified_at: 2022-06-19 17:48:59.526059
